name: ci-dgraph-e2e-net-tests

on:
  push:
    branches: 
    - master
    - dev
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
    branches: 
    - master
    - dev
  workflow_dispatch:

defaults:
  run:
    working-directory: source/Dgraph.tests.e2e

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK 7.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Spin up Dgraph 
      run: |
        mkdir dgraph_data
        docker pull dgraph/standalone:latest
        docker run --name dgraph -d -p "8080:8080" -p "9080:9080" -v dgraph_data:/dgraph dgraph/standalone:latest

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet run --no-restore
